### PR TITLE
Use SteadyTime and SteadyTimer for bond timeouts

### LINKED ISSUE #16: bond breaks on forward time jumps
bond is not robust to forward time jumps, if the time source is updated with a more recent time, every bond breaks (tearing down any process/nodelet relying on it).

Alternatives could be:

1. use monotonic clock for bond timeout:
  - pros: no time jump
  - cons: will timeout if using simulated time for example. If you pause the simulation and restart it, every nodelet will die

2. split the bond period into a bunch of smaller timeouts, and break only if all of them timeout:
  - pros: get rid of the single time jump problem
  - cons: if a time jumps occurs in the last wait of the bond period it will still crash

3. use previous value to detect time jumps, if time jump detected reset the timeout:
  - pros: bond will never break on time jumps whatever ros time source is used
  - cons: arbitrary metric to decide at what threashold a time difference is considered a jump. Should be ok though because the bond period is much smaller than any time jumps done when updating the system clock

I'd lean toward option 3 because it respects the ros time source chosen by the user and should not break in the case of a paused simulated time or the update of the system time on a real system

### PR DESCRIPTION
**Pull request by flixr**
Fixes #16 

Depends on ros/roscpp_core#57 and ros/ros_comm#1014

Tested and working on Ubuntu14.04/Indigo.

### CODE REVIEW

**Review by wjwwood — COMMENTED** [review]
These changes lgtm, but it might require that this repository create a new branch for lunar, if the upstream API addition only gets merged there. It would need to be backported to all supported ROS distributions to avoid any branching in this repository.

It would also be possible to use the preprocessor to conditionally use `SteadyTimer` when it's available from roscpp, but that's up to @mikaelarguedas.

**Comment by mikaelarguedas** [comment]
@flixr I merged some cosmetics fixups on master so I took the liberty of rebasing this branch.
It looks good so far, I have some more testing to do though.
I think the fix is critical enough to be made available for every ros distribution. I'll wait to know if SteadyTimer will be backported for all active ros distros and make the appropriate changes based on this information.

Thanks for providing a fix for this! That's a bug that has certainly been impacting many users

**Review by mikaelarguedas — APPROVED** [review]
LGTM, waiting on approval on https://github.com/ros/ros_comm/pull/1014 and https://github.com/ros/roscpp_core/pull/57 to decide if this can me merged as is or need a distro specific segregation (preprocessor or branching out)

**Comment by mikaelarguedas** [comment]
@mikaelarguedas to either branch out or ifdef to use the new timer only on Lunar

**Comment by mikaelarguedas** [comment]
https://github.com/ros/ros_comm/pull/1014 and https://github.com/ros/roscpp_core/pull/57 have been merged so I'm going to merge this for lunar. thanks @flixr for the valuable contribution, that's a great improvement!

**Pull request merged**
