### PR TITLE
Queue size for a publisher

### PR DESCRIPTION
**Pull request by stonier**
Squash the warning.

### CODE REVIEW

**Comment by tfoote** [comment]
This will need to be tested thoroughly as it will change the threading model for the publishing. 

Also how did you get the number 5? We should push that up at least as a constant at the top of the file or expose it as a parameter, or consider adding it to the constants with the things like timeouts.

**Comment by stonier** [comment]
5...usually what I use as a safe option for most of my python code. I didn't expect the implications to be so strong, especially as it's in the python space. I typically only get meticulous with my c++ code. If I'm using python, I already consider it non-optimal. A little bit naive perhaps :P

We should fill it in nonetheless. Leaving it as the default (`None`) I believe, would replicate the current synchronous behaviour, but this is no longer a recommended option (according to the wiki), so anything else, would as you say, need testing. At 5 is working fine for us, but we're only using bonds in the driver nodelets, 3d sensing nodelets and for this diagnostics testing on relatively good pc's. Not what I'd consider the extreme testing you need.

What has been your usual approach to patching these queue_sizes in core python packages? And your recommendation for this one as I don't have a demanding use case (just the dynamic diagnostics)?

**Comment by tfoote** [comment]
The sizing is mostly to make sure it's not too small so as to drop necessary messages, or to big to cause lag where not wanted. I suspect 5 is reasonable, but would like to confirm that there's not things like multiple publishers possible in the same queue such that if there's 6 bonds on a topic which heartbeat simultaneously 1 gets dropped. And as long as it's a low frequency thing backup on the queue should not be a problem. 

I'm mostly flagging this as it completely changes the underlying publish timing and something like bond with requirements on heartbeats etc the sequencing may be important if there's not a full spin in the background. 

Adding the queue size argument is the way to indicate use asynchronous publishing. Without asynchronous publishing the publish call actually is the thread where the message is delivered. (Which when network dropped etc could freeze the entire process since python doesn't really have threads.) We just need to make sure there is no place where that behavior is being relied upon.

**Comment by stonier** [comment]
Got it.

If it's going to be flagged, pending extra testing, which could be a while... how about setting it to the current behaviour, `None` and create an issue here with the relevant information?

That way the warning has served it's purpose. That is, it has notified the devs who have flagged it and left a reminder to do something, but with note concerns that it would need rigorous testing and is not on the top of the priority mountain right now. The warning then doesn't get in anyone else's way from then on as well.

**Comment by bit-pirate** [comment]
*bump*

**Comment by mikaelarguedas** [comment]
@stonier Hi, I'm taking over this repo and try to catch up on the PRs. As far as I understand, the heartbeat should stop being sent if bond is killed no matter why (crash or voluntary). So I would be more in favour of a queue size of 1 as a default so that if bond stops you don't receive extra heartbeats which have been queued before. What do you think ? Is there something I'm missing ?

I'm going to start looking in the codebase if there is any place where this could cause unexpected/unwanted behaviour and let you know if it looks mergeable to me.

**Comment by stonier** [comment]
A setting of 1 would seem appropriate so long as publishing never happens slower than the heartbeat period. I'm probably not the right person to ask about TCP/IP problems, however a flood of tcp/ip chatter, or a system straining under some other load can cause tcp requests to backup.

Questions:

* Is it imperative that heartbeats are never lost?
* Is there any downside to receiving extra heartbeats after a bond is stopped?

**Comment by tfoote** [comment]
> Is it imperative that heartbeats are never lost?
Any given heartbeat can be lost as long as some heartbeat comes in before the far end times out. 
> Is there any downside to receiving extra heartbeats after a bond is stopped?
Yes, the point of the bond is to detect when the other side goes away. It uses the heartbeat to have positive confirmation the other side is still there. Instead of trying to introspect the communication channel state. (since a hard crashed node may leave the connection open). If there's a large queue and the network is backed up, the heartbeat signals may keep trickling in as the sending queue is emptying thus tricking the remote end into thinking that the bond is still alive. 

I think the choice of a queue size of 1 is the best. It will make sure that there's always something trying to get through if the network is backed up, but will drop any duplicates since the heartbeat is now redundant.

**Comment by mikaelarguedas** [comment]
Agreed, 
@stonier could you update your PR to use a queue size of 1 ? This way we can merge it for kinetic release.

**Comment by stonier** [comment]
updated and squashed

**Comment by mikaelarguedas** [comment]
thanks!

**Comment by dirk-thomas** [comment]
Should this be a kinetic only change or go into indigo and newer? To repeat @tfoote comment:

> It will change the threading model for the publishing.

**Comment by mikaelarguedas** [comment]
given that the only package that should be impacted by this change is image_pipeline. I think we can give it a try on kinetic and if nothing breaks we can backport it to indigo and jade in a later release.
@tfoote do you agree with this strategy ?
@vrabaud do you foresee issues in image_pipeline if this gets release ?

**Comment by vrabaud** [comment]
the use of the word ```bond``` does not qualify as a dependency. image_pipeline is safe :)

**Comment by mikaelarguedas** [comment]
my bad, I just checked packages in desktop-full where "bond" showed up. :confused: 
Only nodelet actually depends on bond. So I guess we'll have to see how many packages depending on nodelet don't work as expected to decide if we backport that change to previous ros distros

**Comment by mikaelarguedas** [comment]
erratum: nodelet uses only bondcpp so won't be impacted by this change. Forget my previous comments.

**Comment by tfoote** [comment]
I think it's worth trying on Kinetic and assuming there are no regressions we can backport it since it does cause notably bad behavior on intermittent networks.

**Pull request merged**
