### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by mgrrx**
Fixes import statement (required for python3)

### CODE REVIEW

**Comment by mjcarroll** [comment]
CI seems to be having trouble with this.  Can you modify it to maintain compatibility with Python2 as well?

**Comment by mgrrx** [comment]
yep, on it

**Comment by mgrrx** [comment]
CI is happy now. I went for package relative imports since these work for both versions

**Comment by mikepurvis** [comment]
Any chance we can get a new tag for this change? Going to be needed for Noetic regardless.

**Pull request merged**
